singleQuote: true
semi: true
useTabs: false
bracketSpacing: true
printWidth: 100
endOfLine: 'auto'
trailingComma: none
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
